### ISSUE TITLE
Move content of User_Config.h to user code

### ISSUE THREAD

**Issue by squix78** [fredericplante/JPEGDecoder#2]
Forgive my nagging but I just want other users to avoid the same problems...
I just updated your code and forgot to change the define in User_Config.h. In my humble opinion this should be part of the user code and not of the library. 
I might have one sketch which wants to use SD card and another SPIFFS. With the current setup I cannot achieve this. Or once I publish my FlightSpotter every single user has to go to the library folder and change the default. This is very error prone...

Again, thank you so much for your work!

**Comment by fredericplante** [comment]
I dont' really mind, this part was the original work of Bodmer, I lefted there to not change much of the code, and since other use the same Technic, not may case, like the author of the UTFT library. Personally I don't really care.

This work is meanted to give JPEG to MCU projects like Arduino, there is no I to that, and changes can be done, without my Ego crying over ;). What matter is that it work and yeah! So no your are not nagging me, nor bothering me. If you feel you can make it better, I would be please.

For so many years, people on Arduino forum were saying that it was impossible, and bla bla bla. My Ego is set to prouve them wrong, not on being the only to be right.

So to be honest, your interest on this project please me, and I'm trilled by the fact that you give time to it, You are welcome to work on this hub. 


Finally, I feel that this routine work kinda like my sister, all his great all along the work, but near the end of the job, anything can come out. :D


Thank you for your interest. (y) 

By the way, I from Québec, so I'm french. My english is not to bad, but I don't care much about this langage and I tend to totally crap it voluntarily, cause it's just part of my cultural heritage to hate this stupid langage. Thank you for you tolérence.

**Comment by fredericplante** [comment]
So basically you are totally welcome to suggest pull requested, and It is more the probable that I will apply your suggestions

**Comment by fredericplante** [comment]
Hem actuelle, I postulate the userconfig thing, it will disapear from the view in sôme exemples àlong the way. And stay there for other aspects.
